from datetime import datetime, timezone
from html import escape
from pathlib import Path

from .engine import calculate_overall_status
from .models import CheckResult, Device


def save_html_report(
    device: Device,
    results: list[CheckResult],
    output_dir: str = "reports",
) -> Path:
    overall_status = calculate_overall_status(results)

    status_class = overall_status.value.lower()

    rows = []

    for result in results:
        details = escape(str(result.details))

        rows.append(
            f"""
            <tr>
                <td>{escape(result.name)}</td>
                <td>
                    <span class="status {result.status.value.lower()}">
                        {escape(result.status.value)}
                    </span>
                </td>
                <td>{escape(result.message)}</td>
                <td>{escape(str(result.value))}</td>
                <td>{details}</td>
            </tr>
            """
        )

    generated_at = datetime.now(timezone.utc).strftime(
        "%Y-%m-%d %H:%M:%S UTC"
    )

    html = f"""
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">

<title>Network Health Report - {escape(device.name)}</title>

<style>
body {{
    font-family: Arial, sans-serif;
    background: #f4f6f8;
    margin: 0;
    padding: 30px;
    color: #1f2937;
}}

.container {{
    max-width: 1400px;
    margin: auto;
}}

.header {{
    background: white;
    padding: 25px;
    border-radius: 12px;
    margin-bottom: 20px;
    box-shadow: 0 2px 8px rgba(0,0,0,0.08);
}}

.header h1 {{
    margin-top: 0;
}}

.summary {{
    display: flex;
    gap: 20px;
    flex-wrap: wrap;
    margin-bottom: 20px;
}}

.card {{
    background: white;
    padding: 20px;
    border-radius: 12px;
    min-width: 180px;
    box-shadow: 0 2px 8px rgba(0,0,0,0.08);
}}

.card h3 {{
    margin-top: 0;
    color: #6b7280;
}}

.status {{
    display: inline-block;
    padding: 5px 10px;
    border-radius: 6px;
    font-weight: bold;
}}

.up {{
    background: #dcfce7;
    color: #166534;
}}

.warning {{
    background: #fef3c7;
    color: #92400e;
}}

.down {{
    background: #fee2e2;
    color: #991b1b;
}}

table {{
    width: 100%;
    border-collapse: collapse;
    background: white;
    border-radius: 12px;
    overflow: hidden;
    box-shadow: 0 2px 8px rgba(0,0,0,0.08);
}}

th {{
    background: #111827;
    color: white;
    text-align: left;
    padding: 14px;
}}

td {{
    padding: 12px;
    border-bottom: 1px solid #e5e7eb;
    vertical-align: top;
}}

tr:hover {{
    background: #f9fafb;
}}

.footer {{
    margin-top: 20px;
    color: #6b7280;
    font-size: 13px;
}}
</style>

</head>

<body>

<div class="container">

<div class="header">
    <h1>Network Health Report</h1>

    <p>
        <strong>Device:</strong>
        {escape(device.name)}
    </p>

    <p>
        <strong>Host:</strong>
        {escape(device.host)}
    </p>

    <p>
        <strong>Device Type:</strong>
        {escape(device.device_type)}
    </p>
</div>

<div class="summary">

    <div class="card">
        <h3>Overall Status</h3>
        <span class="status {status_class}">
            {escape(overall_status.value)}
        </span>
    </div>

    <div class="card">
        <h3>Total Checks</h3>
        <strong>{len(results)}</strong>
    </div>

    <div class="card">
        <h3>UP</h3>
        <strong>
            {sum(1 for r in results if r.status.value == "UP")}
        </strong>
    </div>

    <div class="card">
        <h3>WARNING</h3>
        <strong>
            {sum(1 for r in results if r.status.value == "WARNING")}
        </strong>
    </div>

    <div class="card">
        <h3>DOWN</h3>
        <strong>
            {sum(1 for r in results if r.status.value == "DOWN")}
        </strong>
    </div>

</div>

<table>

<thead>
<tr>
    <th>Check</th>
    <th>Status</th>
    <th>Message</th>
    <th>Value</th>
    <th>Details</th>
</tr>
</thead>

<tbody>

{"".join(rows)}

</tbody>

</table>
<div class="footer">
    Generated by Network Monitoring & Health Check Automation
    <br>
    Generated at: {generated_at}
</div>

</div>

</body>
</html>
"""

    output_path = Path(output_dir)
    output_path.mkdir(parents=True, exist_ok=True)

    report_file = output_path / f"{device.name}_health_report.html"

    report_file.write_text(
        html,
        encoding="utf-8",
    )

    return report_file